In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d

%matplotlib inline

In [2]:
size, alpha, a, b, h, cp, hp, d, cm, hm = np.loadtxt("Silicate_Table.txt", unpack=True)

In [3]:
# New function like a press schechter like, combining a power law and an exponential growth.

# New function including powers between -3, 3
# def function(x,alpha1, beta1, gamma1, alpha2, beta2, gamma2):
def Zcent_func(x, alpha, aa, bb, hh):

    Zcent = aa[:] * (x)**alpha[:] * (1.0 - np.exp(-x/hh[:])) + bb[:]
    
    return Zcent

In [4]:
# New function including powers between -3, 3
# def function(x,alpha1, beta1, gamma1, alpha2, beta2, gamma2):
def function_sigma(x, aa, bb, hh):

    #sigma_par = aa*(1. - np.exp(-np.abs(x[:])/hh)) + bb
    sigma_par = aa[:]*(1. - np.exp(-x/hh[:])) + bb[:]
    
    return sigma_par

In [5]:
G = 1.0e3
T = 1.0e3
ne = 1.0
GTn = G*np.sqrt(T) / ne

In [6]:
Zcent_PDR = Zcent_func(GTn, alpha, a, b, h)

In [7]:
Zwidth_PDR = function_sigma(GTn, cp, d, hp)

In [8]:
print(size)
print(Zcent_PDR)
print(Zwidth_PDR)

[    3.5     5.     10.     50.    100.    500.   1000. ]
[   0.31686269    0.65951336    1.43870486   13.95319359   25.25660814
  115.07957131  214.32006646]
[ 0.5915  0.6198  0.8831  1.6395  2.2399  4.74    6.7213]


In [9]:
error_Zcent = np.abs([(Zcent_PDR[1] - 0.7) / 0.7, (Zcent_PDR[4] - 23.0)/23., (Zcent_PDR[6] - 195.7) / 195.7 ])
error_Zwidth = np.abs([(Zwidth_PDR[1] - 0.5) / 0.62, (Zwidth_PDR[4] - 2.0)/2., (Zwidth_PDR[6] - 6.5) / 6.5 ])


In [17]:
print(error_Zcent*100)
print(error_Zwidth*100)

[  9.07260103   5.9660841   13.46725736]
[ 12.24285714  24.82692308  10.45632184]


In [19]:
print(error_Zcent)
print(error_Zwidth)

[ 0.07320426  0.0498573   0.03751397]
[ 0.19322581  0.11995     0.03404615]


---

In [28]:
size, alpha, a, b, h, cp, hp, d, cm, hm = np.loadtxt("Carbonaceous_Table.txt", unpack=True)

In [29]:
Zcent_PDR = Zcent_func(GTn, alpha, a, b, h)

In [30]:
Zwidth_PDR = function_sigma(GTn, cp, d, hp)

In [31]:
print(size)
print(Zcent_PDR)
print(Zwidth_PDR)

[    3.5     5.     10.     50.    100.    500.   1000. ]
[   0.99034461    1.52701641    3.02094377   26.0484757    44.82365357
  199.90099939  384.12610523]
[ 0.5654  0.7857  1.1786  2.3207  3.2455  6.7832  9.6097]


In [32]:
error_Zcent = np.abs([(Zcent_PDR[1] - 1.4) / 1.4, (Zcent_PDR[4] - 42.3)/42.3, (Zcent_PDR[6] - 348.9) / 348.9 ])
error_Zwidth = np.abs([(Zwidth_PDR[1] - 0.7) / 0.7, (Zwidth_PDR[4] - 2.6)/2.6, (Zwidth_PDR[6] - 8.7) / 8.7 ])

In [33]:
print(error_Zcent*100)
print(error_Zwidth*100)

[  9.07260103   5.9660841   10.09633283]
[ 12.24285714  24.82692308  10.45632184]


In [26]:
print(error_Zcent)
print(error_Zwidth)

[ 0.04053409  0.05255967  0.06431825]
[ 0.11628571  0.22223077  0.11081609]
